In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

In [20]:
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [21]:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [22]:
dataset = dataset.drop("User ID", axis = 1)

In [23]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0         True
1     35            20000          0         True
2     26            43000          0        False
3     27            57000          0        False
4     19            76000          0         True
..   ...              ...        ...          ...
395   46            41000          1        False
396   51            23000          1         True
397   50            20000          1        False
398   36            33000          0         True
399   49            36000          1        False

[400 rows x 4 columns]

In [24]:
x=dataset[['Gender_Male','Age','EstimatedSalary']]
y=dataset['Purchased']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=24)

In [25]:
# Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(x_train ,y_train)
y_pred=GNB.predict(x_test)
GNB_cm = confusion_matrix(y_test , y_pred)
GNB_clf_report = classification_report(y_test,y_pred)

In [26]:
GNB_cm

array([[51,  1],
       [ 2, 26]])

In [27]:
print(GNB_clf_report)

              precision    recall  f1-score   support

           0       0.96      0.98      0.97        52
           1       0.96      0.93      0.95        28

    accuracy                           0.96        80
   macro avg       0.96      0.95      0.96        80
weighted avg       0.96      0.96      0.96        80

In [28]:
# Multinomial Naive Bayes
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB(alpha=1.0, force_alpha=True, fit_prior=True, class_prior=None)
MNB.fit(x_train , y_train)
y_pred=MNB.predict(x_test)
MNB_cm = confusion_matrix(y_test , y_pred)
MNB_clf_report = classification_report(y_test,y_pred)

In [29]:
MNB_cm

array([[48,  4],
       [22,  6]])

In [30]:
print(MNB_clf_report)

              precision    recall  f1-score   support

           0       0.69      0.92      0.79        52
           1       0.60      0.21      0.32        28

    accuracy                           0.68        80
   macro avg       0.64      0.57      0.55        80
weighted avg       0.66      0.68      0.62        80

In [31]:
# Complement Naive Bayes
from sklearn.naive_bayes import ComplementNB
CNB= ComplementNB(alpha=1.0, force_alpha=True, fit_prior=True, class_prior=None, norm=False)
CNB.fit(x_train , y_train)
y_pred=CNB.predict(x_test)
CNB_cm = confusion_matrix(y_test , y_pred)
CNB_clf_report = classification_report(y_test,y_pred)

In [32]:
CNB_cm

array([[22, 30],
       [18, 10]])

In [33]:
print(CNB_clf_report)

              precision    recall  f1-score   support

           0       0.55      0.42      0.48        52
           1       0.25      0.36      0.29        28

    accuracy                           0.40        80
   macro avg       0.40      0.39      0.39        80
weighted avg       0.45      0.40      0.41        80

In [35]:
# Bernoulli Naive Bayes
from sklearn.naive_bayes import BernoulliNB 
BNB= BernoulliNB(alpha=1.0, force_alpha=True, fit_prior=True, class_prior=None)
BNB.fit(x_train , y_train)
y_pred=BNB.predict(x_test)
BNB_cm = confusion_matrix(y_test , y_pred)
BNB_clf_report = classification_report(y_test,y_pred)

/home/lokesh/Loki/Projects/GEN AI/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/lokesh/Loki/Projects/GEN AI/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/lokesh/Loki/Projects/GEN AI/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [36]:
BNB_cm

array([[52,  0],
       [28,  0]])

In [37]:
print(BNB_clf_report)

              precision    recall  f1-score   support

           0       0.65      1.00      0.79        52
           1       0.00      0.00      0.00        28

    accuracy                           0.65        80
   macro avg       0.33      0.50      0.39        80
weighted avg       0.42      0.65      0.51        80

In [38]:
# Categorical Naive Bayes
from sklearn.naive_bayes import CategoricalNB 
CaNB= CategoricalNB (alpha=1.0, force_alpha=True, fit_prior=True, class_prior=None)
CaNB.fit(x_train , y_train)
y_pred=CaNB.predict(x_test)
CaNB_cm = confusion_matrix(y_test , y_pred)
CaNB_clf_report = classification_report(y_test,y_pred)

In [39]:
CaNB_cm

array([[49,  3],
       [10, 18]])

In [40]:
print(CaNB_clf_report)

              precision    recall  f1-score   support

           0       0.83      0.94      0.88        52
           1       0.86      0.64      0.73        28

    accuracy                           0.84        80
   macro avg       0.84      0.79      0.81        80
weighted avg       0.84      0.84      0.83        80