In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv("50_Startups_dataset.csv")
dataset

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,State,Profit
0,0,165349.30,136897.90,471784.20,New York,192261.93
1,1,162597.80,151377.69,443898.63,California,191792.16
2,2,153441.61,101145.65,407934.64,Florida,191050.49
3,3,144372.51,118671.95,383199.72,New York,182902.09
4,4,142107.44,91391.87,366168.52,Florida,166188.04
5,5,131877.00,99814.81,362861.46,New York,156991.22
6,6,134615.56,147198.97,127716.92,California,156122.61
7,7,130298.23,145530.16,323876.78,Florida,155752.70
8,8,120542.62,148719.05,311613.39,New York,152211.87
9,9,123334.98,108679.27,304981.72,California,149760.06
10,10,101913.18,110594.21,229161.05,Florida,146122.05
11,11,100672.06,91790.71,249744.65,California,144259.50
12,12,93863.85,127320.48,249839.54,Florida,141585.62
13,13,91992.49,135495.17,252665.03,California,134307.45
14,14,119943.34,156547.52,256513.02,Florida,132602.75
15,15,114523.71,122616.94,261776.33,New York,129917.14
16,16,78013.21,121597.65,264346.16,California,126993.03
17,17,94657.26,145077.68,282574.41,New York,125370.47
18,18,91749.26,114175.89,294919.67,Florida,124267.00
19,19,86419.80,153514.21,0.10,New York,122776.96
20,20,76253.96,113867.40,298664.57,California,118474.13
21,21,78389.57,153773.53,299737.39,New York,111313.12
22,22,73994.66,122782.85,303319.36,Florida,110352.35
23,23,67532.63,105751.13,304768.83,Florida,108734.09
24,24,77044.11,99281.44,140574.91,New York,108552.14
25,25,64664.81,139553.26,137962.72,California,107404.44
26,26,75328.97,144136.08,134050.17,Florida,105733.64
27,27,72107.70,127864.65,353183.91,New York,105008.41
28,28,66051.62,182645.66,118148.30,Florida,103282.48
29,29,65605.58,153032.16,107138.48,New York,101004.74
30,30,61994.58,115641.38,91131.34,Florida,99937.69
31,31,61136.48,152702.02,88218.33,New York,97483.66
32,32,63408.96,129219.71,46085.35,California,97427.94
33,33,55494.05,103057.59,214634.91,Florida,96779.02
34,34,46426.17,157694.02,210797.77,California,96712.90
35,35,46014.12,85047.54,205517.74,New York,96479.61
36,36,28663.86,127056.31,201126.92,Florida,90708.29
37,37,44070.05,51283.24,197029.52,California,89949.24
38,38,20229.69,65948.03,185265.20,New York,81229.16
39,39,38558.61,82982.19,174999.40,California,81005.86
40,40,28754.43,118546.15,172795.77,California,78240.01
41,41,27893.02,84710.87,164470.81,Florida,77798.93
42,42,23641.03,96189.73,148001.21,California,71498.59
43,43,15505.83,127382.40,35534.27,New York,69759.08
44,44,22177.84,154806.24,28334.82,California,65200.43
45,45,1000.33,124153.14,1904.03,New York,64926.18
46,46,1315.56,115816.31,297114.56,Florida,49490.85
47,47,0.10,135427.02,0.10,California,42559.83
48,48,542.15,51743.25,0.10,New York,35673.51
49,49,0.10,116983.90,45173.16,California,14681.50

In [5]:
dataset.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [6]:
x=dataset[['R&D Spend','Administration','Marketing Spend']]
y=dataset['Profit']

In [7]:
x

    R&D Spend  Administration  Marketing Spend
0   165349.30       136897.90        471784.20
1   162597.80       151377.69        443898.63
2   153441.61       101145.65        407934.64
3   144372.51       118671.95        383199.72
4   142107.44        91391.87        366168.52
5   131877.00        99814.81        362861.46
6   134615.56       147198.97        127716.92
7   130298.23       145530.16        323876.78
8   120542.62       148719.05        311613.39
9   123334.98       108679.27        304981.72
10  101913.18       110594.21        229161.05
11  100672.06        91790.71        249744.65
12   93863.85       127320.48        249839.54
13   91992.49       135495.17        252665.03
14  119943.34       156547.52        256513.02
15  114523.71       122616.94        261776.33
16   78013.21       121597.65        264346.16
17   94657.26       145077.68        282574.41
18   91749.26       114175.89        294919.67
19   86419.80       153514.21             0.10
20   76253.96       113867.40        298664.57
21   78389.57       153773.53        299737.39
22   73994.66       122782.85        303319.36
23   67532.63       105751.13        304768.83
24   77044.11        99281.44        140574.91
25   64664.81       139553.26        137962.72
26   75328.97       144136.08        134050.17
27   72107.70       127864.65        353183.91
28   66051.62       182645.66        118148.30
29   65605.58       153032.16        107138.48
30   61994.58       115641.38         91131.34
31   61136.48       152702.02         88218.33
32   63408.96       129219.71         46085.35
33   55494.05       103057.59        214634.91
34   46426.17       157694.02        210797.77
35   46014.12        85047.54        205517.74
36   28663.86       127056.31        201126.92
37   44070.05        51283.24        197029.52
38   20229.69        65948.03        185265.20
39   38558.61        82982.19        174999.40
40   28754.43       118546.15        172795.77
41   27893.02        84710.87        164470.81
42   23641.03        96189.73        148001.21
43   15505.83       127382.40         35534.27
44   22177.84       154806.24         28334.82
45    1000.33       124153.14          1904.03
46    1315.56       115816.31        297114.56
47       0.10       135427.02             0.10
48     542.15        51743.25             0.10
49       0.10       116983.90         45173.16

In [8]:
y

0     192261.93
1     191792.16
2     191050.49
3     182902.09
4     166188.04
5     156991.22
6     156122.61
7     155752.70
8     152211.87
9     149760.06
10    146122.05
11    144259.50
12    141585.62
13    134307.45
14    132602.75
15    129917.14
16    126993.03
17    125370.47
18    124267.00
19    122776.96
20    118474.13
21    111313.12
22    110352.35
23    108734.09
24    108552.14
25    107404.44
26    105733.64
27    105008.41
28    103282.48
29    101004.74
30     99937.69
31     97483.66
32     97427.94
33     96779.02
34     96712.90
35     96479.61
36     90708.29
37     89949.24
38     81229.16
39     81005.86
40     78240.01
41     77798.93
42     71498.59
43     69759.08
44     65200.43
45     64926.18
46     49490.85
47     42559.83
48     35673.51
49     14681.50
Name: Profit, dtype: float64

In [9]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.20 , random_state=24)

In [10]:
y_test

8     152211.87
5     156991.22
32     97427.94
26    105733.64
19    122776.96
2     191050.49
16    126993.03
40     78240.01
29    101004.74
37     89949.24
Name: Profit, dtype: float64

In [11]:
x_test

    R&D Spend  Administration  Marketing Spend
8   120542.62       148719.05        311613.39
5   131877.00        99814.81        362861.46
32   63408.96       129219.71         46085.35
26   75328.97       144136.08        134050.17
19   86419.80       153514.21             0.10
2   153441.61       101145.65        407934.64
16   78013.21       121597.65        264346.16
40   28754.43       118546.15        172795.77
29   65605.58       153032.16        107138.48
37   44070.05        51283.24        197029.52

In [12]:
reg = AdaBoostRegressor(random_state=24, n_estimators=100)
reg.fit(x_train,y_train)

AdaBoostRegressor(n_estimators=100, random_state=24)

In [13]:
y_pred=reg.predict(x_test)
y_pred

array([138007.28333333, 160712.04666667, 103865.96833333, 110943.9875    ,
       132565.216     , 182902.09      , 112627.2025    ,  84253.61      ,
       104700.252     ,  92696.22571429])

In [14]:
score=r2_score(y_test,y_pred)
score

0.9364876422429483